tasks:
  - name: workshop-graphql-netflix
    before: |
      cd /workspace/workshop-graphql-netflix
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      nvm install 16.13.0
      npm install -g npm@latest
      npm install -g netlify-cli
      npm install
    command: |
      source /home/gitpod/.astra/cli/astra-init.sh
      echo -e "\n\n   *** Astra DB Netflix Clone READY ... Let's go ! ***\n"
      gp open README.md
ports:
  - port: 8080 # Application
    onOpen: ignore
  - port: 8888 # Webpack dev server
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
