image: gitpod/workspace-full
tasks:
  - before: |
    curl -Ls "https://dtsx.io/get-astra-cli" | bash
    npm install -g netlify-cli
  - init: npm install
    command:  astra setup
    name: Setup script
ports:
  - port: 8080 # Application
    onOpen: ignore
  - port: 8888 # Webpack dev server
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
